export type OcrJobMessage = { kind: 'OCR_RECEIPT'; receiptId: string };
export type RewardJobMessage = { kind: 'DELIVER_REWARD'; outboxId: string };
export type JobMessage = OcrJobMessage | RewardJobMessage;

export interface Env {
  ASSETS: Fetcher;
  TICKETS: R2Bucket;
  OCR_JOBS: Queue<OcrJobMessage>;
  REWARD_JOBS: Queue<RewardJobMessage>;
  DB: D1Database;
  AI: Ai;
  IMAGES: ImagesBinding;
  RTALES_BASE_URL: string;
  RTALES_PARENT_ORIGINS: string;
  RTALES_EXTERNAL_GAME_TOKEN: string;
  RTALES_TIMEOUT_MS?: string;
  RTALES_REWARD_MAX_ATTEMPTS?: string;
  DATA_ENCRYPTION_KEY: string;
  OCR_PROVIDER?: string;
  OCR_MODEL: string;
  OCR_WORKERS_AI_FORMAT?: string;
  OCR_MODE: string;
  OCR_API_BASE_URL?: string;
  OCR_API_KEY?: string;
  OCR_TIMEOUT_MS?: string;
  OCR_MAX_ATTEMPTS?: string;
  ALLOW_DEV_ADMIN: string;
  ADMIN_ONLY?: string;
  DEV_ADMIN_TOKEN?: string;
  MAX_TICKET_BYTES: string;
  CLOUDFLARE_ACCOUNT_ID?: string;
  CLOUDFLARE_ACCESS_API_TOKEN?: string;
  CLOUDFLARE_ACCESS_EMAIL_LIST_ID?: string;
  CLOUDFLARE_ACCESS_EMAIL_LIST_NAME?: string;
  ADMIN_BACKOFFICE_URL?: string;
  MAILJET_API_KEY?: string;
  MAILJET_SECRET_KEY?: string;
  MAILJET_FROM_EMAIL?: string;
  MAILJET_FROM_NAME?: string;
}
